# -*- coding: utf-8 -*-
"""Scrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kCKcMR31ZPgDAw6RQS3c_vtGnNe9HW2V
"""

# pip install bing-image-downloader

# pip install simple-image-download

from bing_image_downloader import downloader
import re

"""# Scrapping from bing"""

keywords = ["Hydroponic plant baskets", "Aeroponic plant roots", "Plant growth in aeroponics", "Aeroponic plant baskets"]

folders_names = list (map(lambda item : item.title(), keywords))
folders_names = list (map(lambda item : re.sub(r'\s+', '', item), keywords))

folders_names

for item in folders_names:
  !mkdir $item

for keyword, folder in zip(keywords, folders_names):
  downloader.download(keyword, limit=100,  output_dir=folder, adult_filter_off=True, force_replace=False, timeout=60, verbose=True)